name: Publish
description: Publish to github releases.

inputs:
  alloy:
    description: "Publish Alloy"
    required: false
    default: "true"
  target:
    description: "Rust target"
    required: true
    default: "ubuntu-18.04"

runs:
  using: "composite"
  # Defining the action steps(Just one step to be simple)
  steps:
    - name: Set AlloyDB flag
      shell: bash
      if: ${{ inputs.alloy == 'true' }}
      run: echo REACT_APP_ALLOYDB=true >> "$GITHUB_ENV"

    - name: Compile and release
      uses: rust-build/rust-build.action@v1.4.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        RUSTTARGET: ${{ inputs.target }}
        EXTRA_FILES: "README.md LICENSE"

    - name: Echo AlloyDB flag
      shell: bash
      if: ${{ inputs.alloy == 'true' }}
      run: echo AlloyDB flag ${{ inputs.alloy }}
