name: "Publish"
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - "v*"

jobs:
  publish:
    uses: marcosfpr/ltrs/.github/workflows/publish_template.yml@master
  publish_alloy:
    uses: marcosfpr/ltrs/.github/workflows/publish_template.yml@master
    with:
      alloy: true
