name: "Publish"
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - "v*"

jobs:
  publish:
    uses: marcosfpr/ltrs/.github/workflows/publish_template.yml@release
  # Publish alloy if the tag ends with "-alloy"
  publish-alloy:
    if: endsWith(github.ref, '-alloy')
    uses: marcosfpr/ltrs/.github/workflows/publish_template.yml@release
    with:
      alloy: true
