name: "Publish"
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - "v*"

jobs:
  publish:
    uses: ./.github/workflows/publish_template.yml
  publish_alloy:
    uses: ./.github/workflows/publish_template.yml
    with:
      alloy: true
